Butchery/Butchery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('', include('home.urls', namespace='home')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete")

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Butchery/account/urls.py
from django.urls import path


from . import views

app_name = "account"

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/', views.profile, name="profile"),
]

Butchery/home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    #Leave as empty string for base url
	path('', views.home, name="home"),
	path('contact/', views.contact, name="contact"),
	path('profile/', views.profile, name="profile"),
    ]

Butchery/store/urls.py
from django.urls import path

from . import views

app_name = "store"


urlpatterns = [
    #Leave as empty string for base url
	path('', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
	path('contact/', views.contact, name="contact"),

]

Butchery/templates/home_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoxxMart</title>
    <meta name="description" content="Shop Smart" />
    <meta name="keywords" content="Online shopping mall, online shopping store, online stall, online menu, ecommerce, purchases, delivery, online safe, " />
    <meta name="author" content="Mufudzi Christopher" />
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link id="home_stylesheet" rel="stylesheet" type="text/css" href="{% static 'assets/css/demo.css' %}" />
    <link id="home_stylesheet" rel="stylesheet" type="text/css" href="{% static 'assets/css/component.css' %}" />
    <script src="{% static 'assets/js/modernizr-custom.js' %}"></script>
</head>

<body>
    <!-- navigation -->
    <nav class="pages-nav">
        <div class="pages-nav__item"><a class="link " href="{% url 'store:store' %}">IIIrd Axis</a></div>
        <div class="pages-nav__item"><a class="link " href="">Documentation</a></div>
        <div class="pages-nav__item"><a class="link " href="">Manuals</a></div>
        <div class="pages-nav__item"><a class="link " href="">Software</a></div>
        <div class="pages-nav__item"><a class="link " href="">Customization &amp; Settings</a></div>
        <div class="pages-nav__item"><a class="link " href="">Training</a></div>
        <!--  <div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-buy">Where to buy</a></div>
        <div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-blog">Blog &amp; News</a></div>
        <div class="pages-nav__item pages-nav__item--small"><a class="link link--page link--faded" href="#page-contact">Contact</a></div>   -->
        <div class="pages-nav__item pages-nav__item--social">
            <a class="link link--social link--faded" href="#"><i class="fa fa-twitter"></i><span class="text-hidden">Twitter</span></a>
            <a class="link link--social link--faded" href="#"><i class="fa fa-linkedin"></i><span class="text-hidden">LinkedIn</span></a>
            <a class="link link--social link--faded" href="#"><i class="fa fa-facebook"></i><span class="text-hidden">Facebook</span></a>
            <a class="link link--social link--faded" href="#"><i class="fa fa-youtube-play"></i><span class="text-hidden">YouTube</span></a>
        </div>
    </nav>
    <!-- /navigation-->
    <!-- pages stack -->
    <div class="pages-stack">
        <!-- page -->
        <div class="page" id="page-home">
            <!-- Blueprint header -->
          <header class="bp-header">
                <span class="bp-header__present">Fo<img id="home_spinner" src="{% static 'images/XX-light.gif' %}" style="width:5%" /> Mart <span class="bp-tooltip bp-icon bp-icon--about" data-content="The first of its kind. An online mall. Safe secure payemnts, fast and efficient delivery. All your shopping needs in one place. the smart way to shop. Shop Smart at FoxxMart"></span></span>
            {% if user.is_authenticated %}
            <h5>Logged in as: {{user.username}}
                <h5>
                    <a onclick="darkMode()">
                        <ion-icon title="Dark Mode" name="contrast-outline"></ion-icon>
                    </a>

                    <a onclick="lightMode()">
                        <ion-icon title="Light Mode" name="sunny-outline"></ion-icon>
                    </a>
                    {% endif %}
                    <nav>
                      <a href="" title="Exit Store">
                          <ion-icon name="chevron-left-circle-outline" size="large"></ion-icon>
                      </a>

                        <a href="" title="Information Center">
                            <ion-icon name="information-circle-outline" size="large"></ion-icon>
                        </a>
                        <a href="" title="Contact">
                            <ion-icon name="mail-outline" size="large"></ion-icon>
                        </a>
                        <a href="" title="Home">
                            <ion-icon name="home-outline" size="large"></ion-icon>
                        </a>
                        <a href="" tile="My Cart" data-info="">
                            <ion-icon name="cart-outline" size="large"></ion-icon>
                        </a>
                        {% if user.is_authenticated %}
                        <a href="" title="My  Profile">
                            <ion-icon name="person-outline" size="large"></ion-icon>
                        </a>
                        <a href="" title="Log Out">
                            <ion-icon name="log-out-outline" size="large"></ion-icon>
                        </a>
                        {% else %}
                        <a href="" title="Create Account">
                            <ion-icon name="person-add-outline" size="large"></ion-icon>
                        </a>
                        <a href="" title="Log in">
                            <ion-icon name="log-in-outline" size="large"></ion-icon>
                        </a>
                        {% endif %}
                    </nav>
                    <hr style="color:black">

                    </header>
                    {% block body %}
                    {% endblock %}
                    <img class="poster" src="{% static 'images/logo.png' %}" alt="img01" />
        </div>



        <div class="page">
        </div>
        <div class="page">
        </div>
        <div class="page">
        </div>
        <div class="page">
        </div>
        <div class="page">
        </div>
        <!-- /page -->
    </div>
    <!-- /pages-stack -->
    <button class="menu-button"><span>Menu</span></button>
    <script src="{% static 'assets/js/classie.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>

    <script type="text/javascript">
        document.addEventListener('mousemove', e => {

            let bubles = document.createElement('bubles');
            let x = e.pageX;
            let y = e.pageY;
            bubles.style.left = x + "px";
            bubles.style.top = y + "px";
            let size = Math.random() * 100;
            bubles.style.width = 1 + size + "px";
            bubles.style.height = 1 + size + "px";

            document.body.appendChild(bubles);
            setTimeout(function() {
                bubles.remove();
            }, 1100);
        });





        var home_theme = localStorage.getItem('home_theme')
        var home_spinner = localStorage.getItem('home_spinner')

        console.log("home_theme:", home_theme)
        console.log("home_spinner:", home_spinner)
        if (home_theme == null) {
            lightMode()
        } else {
            document.getElementById('home_stylesheet').href = home_theme

        }


        if (home_spinner == null) {
            lightMode()
        } else {
            document.getElementById('home_spinner').src = home_spinner

        }

        function darkMode() {
            console.log("DarkMode Ran")
            swapStyleDark()
            swapImageDark()
        }

        function swapStyleDark() {
            console.log("Dark Style Ran")
            document.getElementById('home_stylesheet').href = "{% static 'css/demo-dark.css' %}"
            localStorage.setItem('home_theme', "{% static 'css/demo-dark.css' %}")
        }

        function swapImageDark() {
            console.log("Dark Image Ran")
            document.getElementById('home_spinner').src = "{% static 'images/III-dark.gif' }"
            localStorage.setItem('home_spinner', "{% static 'images/III-dark.gif' %}")

        }

        function lightMode() {
            console.log("Light Mode Ran")
            swapStyleLight()
            swapImageLight()

        }

        function swapStyleLight() {
            console.log("Light Style Ran")
            document.getElementById('home_stylesheet').href = "{% static 'css/demo.css' %}"
            localStorage.setItem('home_theme', "{% static 'css/demo.css' %}")
        }

        function swapImageLight() {
            console.log("Light Image Ran")
            document.getElementById('home_spinner').src = "{% static 'images/III-light.gif' %}"
            localStorage.setItem('home_spinner', "{% static 'images/III-light.gif' %}")
        }

    </script>

    <hr style="color:black">
</body>

</html>

Butchery/templates/store_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
  <title>Third Axis</title>
  <meta name="description" content="Blueprint: A responsive product grid layout with touch-friendly Flickity galleries and Isotope-powered filter functionality." />
  <meta name="keywords" content="blueprint, template, layout, grid, responsive, products, store, filter, isotope, flickity" />
  <meta name="author" content="Codrops" />
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap 4  -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <!-- Flaticon icons -->
  <link rel="stylesheet" type="text/css" href="{% static 'font/flaticon.css' %}" />
  <!-- General demo styles & header -->
  <link id="store_stylesheet" rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
  <!-- Flickity gallery styles -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/flickity.css' %}" />

  <script src="{% static 'js/modernizr.custom.js' %}"></script>
  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    const csrftoken = getToken('csrftoken');


    function getCookie(name) {
      //Split cookie string and get all individual name=value pairs in array
      var cookieArr = document.cookie.split(";");

      //Loop through the array elements
      for (var i = 0; i < cookieArr.length; i++) {
        var cookiePair = cookieArr[i].split("=");

        /* Removing whitespace at the begining of the cookie name
        and compare it with the given string */
        if (name == cookiePair[0].trim()) {
          // Decode the cookie value and return
          return decodeURIComponent(cookiePair[1]);
        }
      }
      //Return null if not found
      return null;
    }
    console.log('Cart: ', cart)


    var cart = JSON.parse(getCookie('cart'))

    if (cart == undefined) {
      cart = {}
      console.log('Cart Created!', cart)
      document.cookie = 'cart=' + JSON.stringify(cart) + ";domain;path=/"
    }
    console.log('Cart: ', cart)
  </script>
</head>

<body>

  <hr style="color:black">

  <!-- Blueprint header -->
  <header class="bp-header ">

    <span><img id="store_spinner" src="{% static 'images/III-light.gif' %}" style="width: 5%"/><sup> rd</sup>Axis<span class="bp bp-icon-about" data-content="Ready to eat?"></span></span>

    {% if user.is_authenticated %}
    <h5>Logged in as: {{user.username}}
      <h5>
        <a onclick="darkMode()"><ion-icon title="Dark Mode" name="contrast-outline" ></ion-icon></a>

        <a onclick="lightMode()"><ion-icon title="Light Mode" name="sunny-outline" ></ion-icon></a>



        {% endif %}
        <nav>
          <a href="{% url 'store:store' %}" title="About Us" ><ion-icon name="information-circle-outline" size="large"></ion-icon></a>
          <a href="{% url 'store:contact' %}" title="Contact" ><ion-icon name="mail-outline" size="large"></ion-icon></a>
          <a href="{% url 'store:store' %}" title="Online Store" ><ion-icon name="home-outline" size="large"></ion-icon></a>
          <a href="{% url 'store:cart' %}"  tile="My Cart"data-info=""><ion-icon name="cart-outline" size="large"></ion-icon></a>
          {% if user.is_authenticated %}
          <a href="{% url 'account:profile' %}" title="My  Profile"><ion-icon name="person-outline" size="large"></ion-icon></a>
          <a href="{% url 'account:logout' %}" title="Log Out"><ion-icon name="log-out-outline" size="large"></ion-icon></a>
          {% else %}
          <a href="{% url 'account:register' %}" title="Create Account"><ion-icon name="person-add-outline" size="large"></ion-icon></a>
          <a href="{% url 'account:login' %}" title="Log in"><ion-icon name="log-in-outline"  size="large"></ion-icon></a>
          {% endif %}

        </nav>
        <hr style="color:black">

  </header>


  <div class="content" id="test">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
      <button class="close" data-dismiss="modal"><small><sup>x</sup></small></button>
      {{ message }}
    </div>
    {% endfor %}
    {%  endif %}

    {% block body %}
    {% endblock body %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.0/paper-core.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplex-noise/2.4.0/simplex-noise.min.js"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/flickity.pkgd.min.js' %}"></script>
    <script src="{% static 'js/classie.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="{% static 'js/demo5.js' %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>

    <script type="text/javascript">
    document.addEventListener('mousemove', e=> {

      let bubles = document.createElement('bubles');
      let x = e.pageX;
      let y = e.pageY;
      bubles.style.left = x + "px";
      bubles.style.top = y + "px";
      let size = Math.random() * 100;
      bubles.style.width = 1 + size + "px";
      bubles.style.height = 1 + size + "px";

      document.body.appendChild(bubles);
      setTimeout(function() {
        bubles.remove();
      }, 1100);
    });





    var store_theme = localStorage.getItem('store_theme')
    var store_spinner = localStorage.getItem('store_spinner')

    console.log("store_theme:", store_theme)
    console.log("store_spinner:", store_spinner)
      if (store_theme == null){
        lightMode()
      }else{
        document.getElementById('store_stylesheet').href = store_theme

      }


      if (store_spinner == null){
        lightMode()
      }else{
        document.getElementById('store_spinner').src = store_spinner

      }

      function darkMode(){
            console.log("DarkMode Ran")
            swapStyleDark()
            swapImageDark()
          }
              function swapStyleDark(){
                  console.log("Dark Style Ran")
                  document.getElementById('store_stylesheet').href = "{% static 'css/demo-dark.css' %}"
                  localStorage.setItem('store_theme', "{% static 'css/demo-dark.css' %}")
                }

              function swapImageDark(){
                console.log("Dark Image Ran")
                document.getElementById('store_spinner').src = "{% static 'images/III-dark.gif' }"
                localStorage.setItem('store_spinner', "{% static 'images/III-dark.gif' %}")

                }

        function lightMode(){
          console.log("Light Mode Ran")
          swapStyleLight()
          swapImageLight()

          }
          function swapStyleLight(){
            console.log("Light Style Ran")
            document.getElementById('store_stylesheet').href = "{% static 'css/demo.css' %}"
            localStorage.setItem('store_theme', "{% static 'css/demo.css' %}")
          }

          function swapImageLight(){
            console.log("Light Image Ran")
            document.getElementById('store_spinner').src = "{% static 'images/III-light.gif' %}"
            localStorage.setItem('store_spinner', "{% static 'images/III-light.gif' %}")
          }
        </script>

        <hr style="color:black">
<br><br>

</body>

</html>