Butchery/Butchery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('', include('home.urls', namespace='home')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete")

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Butchery/account/urls.py
from django.urls import path


from . import views

app_name = "account"

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/', views.profile, name="profile"),
]

Butchery/home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    #Leave as empty string for base url
	path('', views.home, name="home"),
	path('contact/', views.contact, name="contact"),
	path('profile/', views.profile, name="profile"),
    ]

Butchery/store/urls.py
from django.urls import path

from . import views

app_name = "store"


urlpatterns = [
    #Leave as empty string for base url
	path('', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
	path('contact/', views.contact, name="contact"),

]

Butchery/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models import Count



# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    firstname = models.CharField(max_length=200, null=True)
    lastname = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(upload_to='profilePictures/', blank=True, null=True)

    def __str__(self):
        return self.firstname

class Product(models.Model):
    name = models.CharField(max_length=200, null=False)
    description = models.TextField(max_length=2000, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    digital = models.BooleanField(default=False, null=False, blank=False)
    image1 = models.ImageField(upload_to='main_product/', blank=True, null=False)

    image2 = models.ImageField(upload_to='main_product/', blank=True, null=False)

    image3 = models.ImageField(upload_to='main_product/', blank=True, null=False)

    image4 = models.ImageField(upload_to='main_product/', blank=True, null=False)

    category = models.ForeignKey('Category' , on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.name

    @property
    def imageURL1(self):
        try:
            url = self.image1.url
        except:
            url = ''
        return url
    def imageURL2(self):
        try:
            url = self.image2.url
        except:
            url = ''
        return url
    def imageURL3(self):
        try:
            url = self.image3.url
        except:
            url = ''
        return url
    def imageURL4(self):
        try:
            url = self.image4.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

class Category(models.Model):
    ## for product category
    category_name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    def save(self , *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super(Category , self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name

Butchery/store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import datetime
from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm

from django.conf import settings

from .models import *
from .forms import *
from .utils import cookieCart, cartData, guestOrder

# Create your views here.
def store(request, category_slug=None):
    data = cartData(request)
    cartItems = data['cartItems']

    category = None
    products = Product.objects.all()
    categorylist = Category.objects.annotate(total_products=Count('product'))
    context = {'cartItems': cartItems, 'products':products , 'category_list' : categorylist ,'category' : category , 'shipping': False}

    return render(request, 'store/store.html', context)



def cart(request):

    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'cartItems': cartItems, 'items': items , 'order': order}

    return render(request, 'store/cart.html', context)

def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'cartItems': cartItems , 'items': items, 'order': order}
    return render(request, 'store/checkout.html', context)

def contact(request):
    if request.method == 'POST':
        message = request.POST['message']
        if request.user.is_authenticated:
            name = request.user.first_name + request.user.last_name
            email = request.user.email
            message = name + "\n" + email + "\n"+ message
            send_mail('Contact Form', message, settings.EMAIL_HOST_USER, ['django10.foxx@gmail.com', 'mcn10.foxx@gmail.com'], fail_silently="false" )
            messages.success(request, ("Your message has been sent successfully..."))
        else:
            name = request.POST['name']
            email = request.POST['email']
            message = name + "\n" + email + "\n"+ message
            send_mail('Contact Form', message, settings.EMAIL_HOST_USER, ['django10.foxx@gmail.com', 'mcn10.foxx@gmail.com'], fail_silently="false" )
            messages.success(request, ("Your message has been sent successfully..."))
        return redirect('store')

    return render(request, 'store/contact.html', {})


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    print('Data: ', request.body)
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()


    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
    return JsonResponse('Payment Complete', safe=False)

Butchery/store/templates/store/cart.html
{% extends 'store_base.html' %}


{% load static %}


{% block body %}
<div class="view">

    <!-- Grid -->

    <section class="grid grid--loader">
        <table class="">
            <thead>
                <tr class="text-center">
                    <th>
                        <h4 class="action--text">&nbsp;</h4>
                    </th>
                    <th>
                        <h4 class="action--text">Item</h4>
                    </th>
                    <th>
                        <h4 class="action--text">Price</h4>
                    </th>
                    <th>
                        <h4 class="action--text">Quantity</h4>
                    </th>
                    <th>
                        <h4 class="action--text">Update</h4>
                    </th>
                    <th>
                        <h4 class="action--text">Total</h4>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in items%}

                <tr>
                    <td>
                        <img class="img slider" src="{{ item.product.imageURL1 }}" style="width: 200px; height: 200px" />
                    </td>

                    <td>
                        <strong class="action--text">{{item.product.name}}</strong>
                    </td>
                    <td>
                        <strong class="action--text">R{{item.product.price|floatformat:2}}</strong>
                    </td>

                    <td>
                        <strong class="action--text">{{item.quantity}}</strong>
                    </td>
                    <td>
                        <ion-icon data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" size="large" name="chevron-up-circle-outline"></ion-icon>
                        <hr>
                        <ion-icon data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" size="large" name="chevron-down-circle-outline"></ion-icon>
                    </td>
                    <td>
                        <h4><strong class="action--text">{{item.get_total}}</strong></h4>
                    </td>
                </tr><!-- END TR-->

                {% endfor %}

            </tbody>
        </table>

        <div class="row justify-content-end">
            <div class=" cart-wrap ftco-animate">
                <div class="cart-total mb-3">
                  <br>
                    <h3>Cart Totals</h3>
                    <hr>

                    <p class="d-flex">
                        <span>Items: &nbsp;</span>
                        <span><strong>{{order.get_cart_items}}</strong></span>
                    </p>
                    <p class="d-flex total-price">
                        <span>Total:&nbsp; </span>
                        <span><strong> R{{order.get_cart_total|floatformat:2}} </strong></span>
                    </p>
                    <hr>

                </div>
                <p><a href="{% url 'store:store' %}" class="btn action--button-btn">Continue Shopping&nbsp;&nbsp;</a>&nbsp;{% if order.get_cart_total%}<a {% if user.is_authenticated %} href="{% url 'store:checkout' %}" {% else %} href="{% url 'account:register' %}" {% endif %}class="btn action--button-btn">Proceed to Checkout &nbsp;&nbsp; </a>
                    {% endif %}</p>
            </div>
        </div>
    </section>

    {% endblock %}

Butchery/store/templates/store/checkout.html
{% extends 'store_base.html' %}


{% load static %}

{% block body %}

<div class="view">

    <!-- Grid -->

    <section class="grid grid--loader">
        <div class=" p-3 p-md-4">
            <h3 class="billing-heading mb-4 action--text">Order Summary</h3>
            <p class="billing-heading mb-4 action--text">Number of Items : <strong>{{ order.get_cart_items}}</strong></p>
                <p class="billing-heading mb-4 action--text">Grand Total : <strong>R{{ order.get_cart_total}}</strong></p>
                    <span> {% for item in items %} <img src={{ item.product.imageURL1}} class="slider" style="width:100px; height:120px" /> X {{item.quantity}}&nbsp{% endfor %}<span>

                            <div>

                              <br>
                                    <div style="padding-right: 30%;padding-left: 30%">

                                        <div id="paypal-button-container"></div>

                                </div>

                            </div>
                            <br>

                            <p class="action--text"><a href="{% url 'store:cart' %}" class="btn action--button-btn">Return to Cart</a>
                                <a href="{% url 'store:store' %}" class="btn action--button-btn">Continue Shopping</a></p>
        </div>
    </section>

</div>
<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=AZCNMqNFWTke_HKbXs8LZXyXA8dyQK_cwrjnyypRZrRkiGhIicTMpZpbYhbWzt6WYZ-TmsWWbSgEE5Hx&currency=USD"></script>

<script>
    var total = '{{order.get_cart_total}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'blue',
            label: 'pay',
            height: 40
        },

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                submitFormData();
            });
        }


    }).render('#paypal-button-container');

</script>



<script type="text/javascript">
    var shipping = '{{order.shipping}}'
    var total = '{{order.get_cart_total}}'

    console.log('Shipping value:', shipping)
    console.log('Shipping total:', total)

    if (shipping == 'False') {
        document.getElementById('shipping-information').innerHTML = ''
    }

    if (user != 'AnonymousUser') {
        document.getElementById('user-information').innerHTML = ''
    }

    if (shipping == 'False' && user != 'AnonymousUser') {
        //Hide entire form if logged in and shipping false
        document.getElementById('form-wrapper').classList.add("hidden");
        //show payment if logged in user in user wants to buy an item that does not require shipping
        document.getElementById('payment-info').classList.remove("hidden");
    }


    var form = document.getElementById('form')
    csrf_token = form.getElementsByTagName("input")[0].value

    form.addEventListener('submit', function(e) {
        e.preventDefault()
        console.log('Form Submitted. . . .')
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden')
    })
    /*
      document.getElementById('make-payment').addEventListener('click', function(e) {
        submitFormData()
      })
    */
    function submitFormData() {
        console.log('Payment button clicked')

        var userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }
        console.log('User Form Created')

        var shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null,
        }
        console.log('Shipping Info Created')

        if (shipping != 'False') {
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }
        console.log('Checks passed')
        console.log('User Form Data', userFormData)
        console.log('Shipping Information', shippingInfo)

        var url = '/process_order/'
        fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({
                    'form': userFormData,
                    'shipping': shippingInfo
                })
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction completed');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain;path=/"

                window.location.href = "{% url 'store:store' %}"
            })
    }

</script>

{% endblock %}

Butchery/store/templates/store/contact.html
{% extends 'store_base.html' %}


{% load static %}


{% block body %}
<div class="view">

  <!-- Grid -->

  <section class="grid grid--loader">

    <h2> Contact Us </h2>

<div class="container-contact100">

  <div class="wrap-contact1000">

    <form class="contact100-form validate-form" method="post">

      {% csrf_token %}

      <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Name is required">
        <span class="label-input100">Your Name</span>
{% if user.is_authenticated %}<p> {{ user.first_name}}&nbsp; {{ user.last_name}} </p> {% else %} <input class="input100" type="text" name="name"  placeholder="Enter your name">{% endif %}


        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
        <span class="label-input100">Email</span>
        {% if user.is_authenticated %}<p> {{ user.email}}</p> {% else %}  <input class="input100" type="text" name="email" placeholder="Enter your email addess">{% endif %}

        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input" data-validate = "Message is required">
        <span class="label-input100">Message</span>
        <textarea class="input100" name="message" placeholder="Your message here..."></textarea>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <button class="action--button-btn action">
          <span>
            Submit
            <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
          </span>
        </button>
      </div>
    </form>

    <span class="contact100-more">
      For any question contact our 24/7 call center: <span class="contact100-more-highlight">+27 21 555 5544</span>
    </span>
  </div>
</div>
</section>
</div>

<script type="text/javascript">

  (function ($) {
      "use strict";

      /*==================================================================
      [ Focus Contact2 ]*/
      $('.input100').each(function(){
          $(this).on('blur', function(){
              if($(this).val().trim() != "") {
                  $(this).addClass('has-val');
              }
              else {
                  $(this).removeClass('has-val');
              }
          })
      })

      /*==================================================================
      [ Validate ]*/
      var input = $('.validate-input .input100');

      $('.validate-form').on('submit',function(){
          var check = true;

          for(var i=0; i<input.length; i++) {
              if(validate(input[i]) == false){
                  showValidate(input[i]);
                  check=false;
              }
          }

          return check;
      });


      $('.validate-form .input100').each(function(){
          $(this).focus(function(){
             hideValidate(this);
          });
      });

      function validate (input) {
          if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {
              if($(input).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/) == null) {
                  return false;
              }
          }
          else {
              if($(input).val().trim() == ''){
                  return false;
              }
          }
      }

      function showValidate(input) {
          var thisAlert = $(input).parent();

          $(thisAlert).addClass('alert-validate');
      }

      function hideValidate(input) {
          var thisAlert = $(input).parent();

          $(thisAlert).removeClass('alert-validate');
      }


      /*==================================================================
      [ Show / hide Form ]*/

      $('.contact100-btn-hide').on('click', function(){
          $('.wrap-contact100').fadeOut(400);
      })

      $('.contact100-btn-show').on('click', function(){
          $('.wrap-contact100').fadeIn(400);
      })

  });
  </script>
{% endblock %}

Butchery/store/templates/store/store.html
{% extends 'store_base.html' %}


{% load static %}




{% block body %}
<!-- Blueprint header -->
<!-- Compare basket -->
<div class="compare-basket">
  <button class="action action---button action--compare"><i class="fa fa-check"></i><span class="action__text">Compare</span></button>
</div>



<!-- Bottom bar with filter and cart info -->
<div class="bar">
  <div class="filter">
    <span class="filter__label">Filter: </span>
    <button class="action filter__item filter__item--selected" data-filter="*">All</button>

    {% for category in category_list %}

    <button class="action filter__item" data-filter=".{{category}}">
      <i class="icon icon--{{category}}"></i>
      <span class="action__text">{{category}}</span>
    </button>

    {% endfor %}

  </div>
<a href="{% url 'store:cart' %}" class="">  <button class="cart"> <i class=" cart__icon fa fa-shopping-cart "></i>
      <span class="text-hidden">Shopping cart</span>
      <span class="cart__count">{{cartItems}}</span>
  </button></a>
</div>

<div class="view">

  <!-- Grid -->

  <section class="grid grid--loader">
    <!-- The cursor elements -->
    <div class="cursor cursor--small"></div>
    <canvas class="cursor cursor--canvas" resize></canvas>
    <!-- Loader -->
    <img class="grid__loader" src="{% static 'images/grid.svg' %}" width="60" alt="Loader image" />
    <!-- Grid sizer for a fluid Isotope (Masonry) layout -->
    <div class="grid__sizer"></div>
    <!-- Grid items -->


    {% for product in products %}
    <div class="grid__item {{product.category}} product">



      <div class="slider product__image">
        <div class="slider__item"><img src="{{product.imageURL1}}" /></div>
        <div class="slider__item"><img src="{{product.imageURL2}}" /></div>
        <div class="slider__item"><img src="{{product.imageURL3}}" /></div>
        <div class="slider__item"><img src="{{product.imageURL4}}" /></div>
      </div>


      <div class="product__info  meta">
        <span class=" product__title meta__title">{{product.name}}</span>
        <img class="product__image extra" src="{{product.imageURL1}}" alt="{{product.name}}" />
        <span class="product__year extra" style="color: #000">{{product.description}}</span>
        <span class="product__price  meta__price" >R{{product.price|floatformat:2}}</span>
        <!--       <span class="product__alcohol extra highlight">{{product.description}}</span> -->

      </div>
      <label class="action action--button action--compare-add"><input class="check-hidden" type="checkbox" /><i class="fa fa-plus"></i><i class="fa fa-check"></i><span class="action__text--invisible">Add to compare</span></label>
      <button data-product={{product.id}} data-action="add" class="action action--button action--compare-buy action--buy update-cart"><i class="fa fa-shopping-cart"></i><span class="action__text--invisible">Add to cart</span></button>
    </div>

    {% endfor %}

    <!-- /grid-->
</div>
<!-- /view -->
<!-- product compare wrapper -->
<section class="compare">
  <button class="action action--close"><i class="fa fa-remove"></i><span class="action__text action__text--invisible">Close comparison overlay</span></button>
</section>



{% endblock body %}