Butchery/Butchery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('store/', include('store.urls', namespace='store')),
    path('', include('home.urls', namespace='home')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete")

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Butchery/account/urls.py
from django.urls import path


from . import views

app_name = "account"

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/', views.profile, name="profile"),
]

Butchery/home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    #Leave as empty string for base url
	path('', views.home, name="home"),
	path('contact/', views.contact, name="contact"),
	path('profile/', views.profile, name="profile"),
    ]

Butchery/home/models.py
from django.db import models

# Create your models here.

Butchery/home/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def home(request):

    context = {}
    return render(request, 'home/index.html', context)

def contact(request):
    if request.method == 'POST':
        message = request.POST['message']
        if request.user.is_authenticated:
            name = request.user.first_name + request.user.last_name
            email = request.user.email
            message = name + "\n" + email + "\n"+ message
            send_mail('Contact Form', message, settings.EMAIL_HOST_USER, ['django10.foxx@gmail.com', 'mcn10.foxx@gmail.com'], fail_silently="false" )
            messages.success(request, ("Your message has been sent successfully..."))
        else:
            name = request.POST['name']
            email = request.POST['email']
            message = name + "\n" + email + "\n"+ message
            send_mail('Contact Form', message, settings.EMAIL_HOST_USER, ['django10.foxx@gmail.com', 'mcn10.foxx@gmail.com'], fail_silently="false" )
            messages.success(request, ("Your message has been sent successfully..."))
        return redirect('home:home')

    return render(request, 'home/contact.html', {})

def profile(request):
    if request.user.is_authenticated:

        return render(request, 'home/profile.html', {})
    else:
        return redirect('home:home')



def edit_profile(request):
    if request.user.is_authenticated:
        return render(request, 'home/edit_profile.html', context)

    else:
        return redirect('account:login')

Butchery/home/templates/home/contact.html
{% extends 'home_base.html' %}


{% load static %}


{% block body %}
<div class="view">

  <!-- Grid -->

  <section class="grid grid--loader">

    <h2> Contact Us </h2>

<div class="container-contact100">

  <div class="wrap-contact1000">

    <form class="contact100-form validate-form" method="post">

      {% csrf_token %}

      <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Name is required">
        <span class="label-input100">Your Name</span>
{% if user.is_authenticated %}<p> {{ user.first_name}}&nbsp; {{ user.last_name}} </p> {% else %} <input class="input100" type="text" name="name"  placeholder="Enter your name">{% endif %}


        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
        <span class="label-input100">Email</span>
        {% if user.is_authenticated %}<p> {{ user.email}}</p> {% else %}  <input class="input100" type="text" name="email" placeholder="Enter your email addess">{% endif %}

        <span class="focus-input100"></span>
      </div>

      <div class="wrap-input100 validate-input" data-validate = "Message is required">
        <span class="label-input100">Message</span>
        <textarea class="input100" name="message" placeholder="Your message here..."></textarea>
        <span class="focus-input100"></span>
      </div>

      <div class="container-contact100-form-btn">
        <button class="action--button-btn action">
          <span>
            Submit
            <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
          </span>
        </button>
      </div>
    </form>

    <span class="contact100-more">
      For any question contact our 24/7 call center: <span class="contact100-more-highlight">+27 21 555 5544</span>
    </span>
  </div>
</div>
</section>
</div>

<script type="text/javascript">

  (function ($) {
      "use strict";

      /*==================================================================
      [ Focus Contact2 ]*/
      $('.input100').each(function(){
          $(this).on('blur', function(){
              if($(this).val().trim() != "") {
                  $(this).addClass('has-val');
              }
              else {
                  $(this).removeClass('has-val');
              }
          })
      })

      /*==================================================================
      [ Validate ]*/
      var input = $('.validate-input .input100');

      $('.validate-form').on('submit',function(){
          var check = true;

          for(var i=0; i<input.length; i++) {
              if(validate(input[i]) == false){
                  showValidate(input[i]);
                  check=false;
              }
          }

          return check;
      });


      $('.validate-form .input100').each(function(){
          $(this).focus(function(){
             hideValidate(this);
          });
      });

      function validate (input) {
          if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {
              if($(input).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/) == null) {
                  return false;
              }
          }
          else {
              if($(input).val().trim() == ''){
                  return false;
              }
          }
      }

      function showValidate(input) {
          var thisAlert = $(input).parent();

          $(thisAlert).addClass('alert-validate');
      }

      function hideValidate(input) {
          var thisAlert = $(input).parent();

          $(thisAlert).removeClass('alert-validate');
      }


      /*==================================================================
      [ Show / hide Form ]*/

      $('.contact100-btn-hide').on('click', function(){
          $('.wrap-contact100').fadeOut(400);
      })

      $('.contact100-btn-show').on('click', function(){
          $('.wrap-contact100').fadeIn(400);
      })

  });
  </script>
{% endblock %}

Butchery/home/templates/home/index.html
{% extends 'home_base.html' %}


{% load static %}


{% block body %}


{% endblock %}

Butchery/home/templates/home/profile.html
{% extends 'home_base.html' %}

{% load static %}

{% block body %}


<!-- Main -->
<div class="view">

    <!-- Grid -->

    <section class="grid" id="main">
        <header>
            <span class="avatar"><img {% if request.user.customer.profile_pic %} src="{{request.user.customer.profile_pic.url}}" {% else %} src="{% static 'images/dummy.jpg' %}" {% endif %} alt="" /></span>
            <h3>{{user.first_name}}&nbsp;{{user.last_name}}</h3>
            <h5 style="text-decoration: underline; font-weight: 400">{{user.username}}</h5>
<br>
            <ul class="icons">
                <li><a title="Edit Profile" href="{% url 'account:edit_profile' %}">
                        <ion-icon name="create-outline" size="large">Edit Information</ion-icon>
                    </a></li>
                <li><a title="Change Password" href="{% url 'account:change_password' %}">
                        <ion-icon name="lock-open-outline" size="large">Update Password</ion-icon>
                    </a></li>
            </ul>
        </header>
        <br>
        <!--
        <h2>Previous orders</h2><br>
        <table>
            <thead>
                <tr>
                    <th class="action--text">Transaction ID</th>
                    <th class="action--text">Date Ordered</th>
                    <th class="action--text">Order Total</th>
                    <th class="action--text">Order Status </th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}

                <tr class="">
                    <td>
                        <h4 class="action--text">{{order.transaction_id}}</h4>
                    </td>

                    <td>
                        <h4 class="action--text">{{order.date_ordered}}
                        </h4>
                    </td>
                    <td>
                        <h4 class="action--text">R{{ order.get_cart_total}}</h4>
                    </td>
                    <td>
                        {% if order.complete %}
                        <p class="action--text">Order Completed</p>
                        {% endif %}
                        {% if not order.complete %}
                        <p class="action--text">Order Pending</p>
                        {% endif %}
                    </td>

                    <td class="total"><strong class="action--text">{{item.get_total}}</strong></td>
                </tr><!-- END TR--
                {% endfor %}


            </tbody>
        </table>-->

    </section>


</div>
<script type="text/javascript">
    console.log("You have reached the Profile page")

</script>


{% endblock %}